### PR TITLE
Import concrete NIO modules

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
We should import the correct NIO submodules instead of the umbrella.

# Modification
Fix up import statements.

# Result
We are now importing the proper submodules

### CODE REVIEW

**Comment by glbrntt** [comment]
@swift-server-bot add to allowlist

**Comment by glbrntt** [comment]
@swift-server-bot test this please

**Review by glbrntt — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Review by dnadoba — APPROVED** [review]

**Comment by glbrntt** [comment]
@swift-server-bot test this please

**Comment by glbrntt** [comment]
@swift-server-bot add to allowlist

**Pull request merged**
