### PR TITLE
Add Android support

### PR DESCRIPTION
**Pull request by buttaface**
Android doesn't have `getpass()` either.

@Joannis, submitted as you asked for.

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
LGTM, thanks!

**Comment by Lukasa** [comment]
@swift-server-bot add to allowlist

**Comment by buttaface** [comment]
CI failures are unrelated.

**Comment by Lukasa** [comment]
They are indeed: we reduced allocations in NIO so the tests need to be updated. I'll put up a PR shortly.

**Comment by Lukasa** [comment]
See #135.

**Pull request merged**
